language: node_js
node_js:
  - "stable"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - npm test -- --coverage --watchAll=false
  - npm run build

after_script:
  - npm install -g codecov
  - codecov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

cache:
  directories:
    - node_modules
